### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [kimgarrard/frontend-data#14]
Hi Kim, je werkt erg netjes, en ik vind je code ook prima leesbaar en begrijpelijk, ik zou hem wel nog even door een beautifier halen zodat je willekeurige spaties en incorrecte tabs qua indentatie eruit kan halen, verder mis ik een .gitignore waarin je bijvoorbeeld je .DS_Store bestand uit je git repository kan houden.

**Comment by kimgarrard** [comment]
Hi Robert, heel erg bedankt voor je feedback! Gitignore heb ik wel toegevoegd, maar deze lijkt helaas niet te werken.
