### ISSUE TITLE
Schrijf meer commits

### ISSUE THREAD

**Issue by kriskuiper** [kimgarrard/frontend-data#19]
Lijkt er nu een beetje op dat je je commits schrijft a la: initialize project..... finish project. Committen wil je liever veel doen en de commits zelf wil je klein houden (a.k.a. . 

Uiteraard is het meer een workflow dingetje maar neem het vooral als tip mee want er gaat een keer komen dat je een commit hebt verkracht, als je dan wil terugzetten ben je niet 2/3 van je project kwijt.

**Comment by kimgarrard** [comment]
Dankzij jouw hulp kan ik nu pushen, dus doe dat nu vaker
