### ISSUE TITLE
Missende dingen in je repo

### ISSUE THREAD

**Issue by lennartdeknikker** [kimgarrard/frontend-data#20]
- [ ] je readme moet nog toegevoegd worden
- [ ] als je je bestanden hebt gepushed, kun je het publiceren op github pages of netlify en de link aan je repo toevoegen. 
- [ ] Ook een korte omschrijving mist nog.
- [ ] In een .gitignore bestand kun je je dist map toevoegen en .cache en andere bestanden die niet in je repo horen.

**Comment by kimgarrard** [comment]
Alles gefixt, behalve de .gitignore. Deze heb ik wel toegevoegd, maar werkt helaas niet
